version: '3.7'

services:
  postgres_onder_mpp:
    image: 'postgres:9.4'
    volumes:
      - postgresql-volume-mpp:/var/lib/postgresql/data
      - ./pg_init.sql:/docker-entrypoint-initdb.d/1-pg_init.sql
    ports:
      - 5432:5432

volumes:
  postgresql-volume-mpp:
    driver: local
